# Generated by Django 6.0.4 on 2026-04-23 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('numero_tel', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('portfolio', 'Portfolio'), ('linkedin', 'LinkedIn')], default='portfolio', max_length=20)),
                ('url', models.CharField(max_length=255)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.perfil')),
            ],
            options={
                'db_table': 'Link',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tipo'), name='unique_link_por_tipo')],
            },
        ),
    ]
