# Generated by Django 6.0.4 on 2026-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aptitudes',
            field=models.TextField(blank=True),
        ),
    ]
