# Generated by Django 6.0.4 on 2026-04-23 16:12

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_perfil_aptitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.save_profile_image),
        ),
    ]
