# Generated by Django 6.0.4 on 2026-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
