# Generated by Django 6.0.4 on 2026-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
