# Generated by Django 6.0.4 on 2026-05-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_mensaje_imagen'),
    ]

    operations = [
    ]
