# Generated by Django 6.0.4 on 2026-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='img',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
