# Generated by Django 6.0.4 on 2026-04-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_publicacion_update_at_publicacion_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='img',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
