# Generated by Django 6.0.4 on 2026-05-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_comentario_publicacion_alter_comentario_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='img',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='feed.publicacion')),
            ],
        ),
    ]
