# Generated by Django 6.0.4 on 2026-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_remove_publicacion_img_alter_publicacion_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
